<a href="https://colab.research.google.com/github/kdh7979/simple-nmt/blob/master/_9_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98(PyTorch)_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치(PyTorch)

<img src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbuUgoV%2FbtqwWZvcHHX%2Fd6XzIFBEfiuFb0UvyV4A50%2Fimg.jpg" width="300">

- 코드 출처: https://pytorch.org/tutorials/

## 파이토치의 구성요소

- `torch`: 텐서를 생성하는 라이브러리

- `torch.autograd`: 자동미분 기능을 제공하는 라이브러리

- `torch.nn`: 신경망을 생성하는 라이브러리

- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리

- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공

- `torch.legacy`(./nn/.optim): Torch로부터 포팅해온 코드

- `torch.onnx`: ONNX(Open Neural Network Exchange)

  - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 넘파이(NumPy)의 ndarray와 유사

- GPU를 사용한 연산 가속도 가능

In [ ]:
import torch

In [ ]:
torch.__version__

'1.9.0+cu102'

### 초기화 되지 않은 행렬 

In [ ]:
x = torch.empty(4,2)
x

tensor([[1.8764e+15, 3.0896e-41],
        [1.5198e+12, 3.0896e-41],
        [2.6625e-44, 0.0000e+00],
        [       nan,        nan]])

### 무작위로 초기화된 행렬

In [ ]:
x = torch.rand(4,2)
x

tensor([[0.0887, 0.0072],
        [0.0963, 0.0480],
        [0.9852, 0.2332],
        [0.9055, 0.5599]])

### dtype이 long, 0으로 채워진 텐서

In [ ]:
x = torch.zeros(4, 2, dtype=torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
x = torch.tensor([3, 2.3])
x

tensor([3.0000, 2.3000])

In [ ]:
x = x.new_ones(2, 4 ,dtype = torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [ ]:
x = torch.randn_like(x, dtype = torch.double)
x

tensor([[ 0.9613,  1.8737,  0.3870,  0.8860],
        [-0.2085,  1.3938, -1.4341, -1.9022]], dtype=torch.float64)

### 텐서의 크기

In [ ]:
x.size()

torch.Size([2, 4])

## 텐서의 연산(operations)

### 덧셈 1

In [ ]:
y = torch.rand(2,4)

In [ ]:
print(y)
print(x+y)

tensor([[0.2736, 0.0300, 0.5377, 0.8922],
        [0.5515, 0.6707, 0.4837, 0.2955]])
tensor([[ 1.2349,  1.9036,  0.9247,  1.7782],
        [ 0.3430,  2.0645, -0.9504, -1.6067]], dtype=torch.float64)


### 덧셈2

In [ ]:
torch.add(x, y)

tensor([[ 1.2349,  1.9036,  0.9247,  1.7782],
        [ 0.3430,  2.0645, -0.9504, -1.6067]], dtype=torch.float64)

### 덧셈3
- 결과 텐서를 인자로 제공

In [ ]:
print(x)
print(y)
y.add_(x)   #y+=x
print(y)

tensor([[ 0.9613,  1.8737,  0.3870,  0.8860],
        [-0.2085,  1.3938, -1.4341, -1.9022]], dtype=torch.float64)
tensor([[0.2736, 0.0300, 0.5377, 0.8922],
        [0.5515, 0.6707, 0.4837, 0.2955]])
tensor([[ 1.2349,  1.9036,  0.9247,  1.7782],
        [ 0.3430,  2.0645, -0.9504, -1.6067]])


### 덧셈4
- `in-place` 방식

- (참고) in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

### 그 외의 연산
- `torch.sub` : 뺄셈

- `torch.mul` : 곱셉

- `torch.div` : 나눗셈

- `torch.mm` : 내적(dot product)

In [ ]:
x = torch.Tensor([[1, 3],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x-y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [ ]:
x = torch.Tensor([[1, 3],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x*y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [ ]:
x = torch.Tensor([[1, 3],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x/y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [ ]:
x = torch.Tensor([[1, 3],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(torch.mm(x, y))   #행렬곱

tensor([[20., 28.],
        [52., 76.]])


## 텐서의 조작(manipulations)

### 인덱싱
- 넘파이처럼 인덱싱 사용가능

In [ ]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [ ]:
print(x[:, 1])  #x[행슬라이싱, 열슬라이싱]
print(x[1, :])

tensor([3., 7.])
tensor([5., 7.])


### view
- 텐서의 크기(size)나 모양(shape)을 변경

In [ ]:
x = torch.randn(4, 5)
y = x.view(20)      #20 by 1
z = x.view(5, -1)   #5 by 자동

print(x)
print(y)
print(z)

tensor([[-0.1422,  0.7073,  0.0385,  1.8141,  0.9374],
        [-0.7146,  0.2042,  0.3087, -0.4283, -0.4724],
        [-0.0272, -1.0399,  0.1380, -0.2501, -1.5147],
        [ 0.6883, -0.4069,  0.2968, -0.9622, -0.7817]])
tensor([-0.1422,  0.7073,  0.0385,  1.8141,  0.9374, -0.7146,  0.2042,  0.3087,
        -0.4283, -0.4724, -0.0272, -1.0399,  0.1380, -0.2501, -1.5147,  0.6883,
        -0.4069,  0.2968, -0.9622, -0.7817])
tensor([[-0.1422,  0.7073,  0.0385,  1.8141],
        [ 0.9374, -0.7146,  0.2042,  0.3087],
        [-0.4283, -0.4724, -0.0272, -1.0399],
        [ 0.1380, -0.2501, -1.5147,  0.6883],
        [-0.4069,  0.2968, -0.9622, -0.7817]])


### item
- 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())     #텐서에 실제 존재하는 값 반환
print(x.dtype)

tensor([-0.7855])
-0.7855201959609985
torch.float32


- 스칼라값 하나만 존재해야함

In [ ]:
x = torch.randn(2)
print(x)

tensor([-0.1213,  1.0394])


In [ ]:
x.item()    #스칼라여야함

ValueError: ignored

### squeeze 
- 차원을 축소(제거)

In [ ]:
tensor = torch.rand(1, 3, 3)
print(tensor)
tensor.shape

tensor([[[0.3938, 0.2113, 0.4519],
         [0.7096, 0.5742, 0.7584],
         [0.9388, 0.8937, 0.7563]]])


torch.Size([1, 3, 3])

In [ ]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.3938, 0.2113, 0.4519],
        [0.7096, 0.5742, 0.7584],
        [0.9388, 0.8937, 0.7563]])
torch.Size([3, 3])


### unsqueeze
- 차원을 증가(생성)

In [ ]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.2858, 0.0606, 0.2078],
         [0.8528, 0.7201, 0.6224],
         [0.5966, 0.7604, 0.8808]]])
torch.Size([1, 3, 3])


In [ ]:
t = tensor.unsqueeze(dim=0)
print(t)
print(t.shape)

tensor([[[[0.2858, 0.0606, 0.2078],
          [0.8528, 0.7201, 0.6224],
          [0.5966, 0.7604, 0.8808]]]])
torch.Size([1, 1, 3, 3])


### stack
- 텐서간 결합

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### cat
- 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 dim이 존재해야함
  - 예를 들어, 해당 차원을 늘려준 후 결합


In [ ]:
a = torch.rand(1, 1, 3, 3)
b = torch.rand(1, 1, 3, 3)
c = torch.cat((a,b), dim=0) #dim : 어떤 차원과 연결할 것인지

print(c)
print(c.shape)

tensor([[[[0.5803, 0.2327, 0.4172],
          [0.8218, 0.7242, 0.1901],
          [0.0728, 0.4569, 0.5002]]],


        [[[0.2744, 0.4021, 0.7505],
          [0.6068, 0.8731, 0.0108],
          [0.6236, 0.7985, 0.3686]]]])
torch.Size([2, 1, 3, 3])


### chunk
- 텐서를 여러 개로 나눌 때 사용

- 몇 개의 텐서로 나눌 것이냐

In [ ]:
tensor = torch.rand(3, 6)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1)  #분할할 개수 : 3

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.5677, 0.1248, 0.6938, 0.7746, 0.0696, 0.1232],
        [0.1400, 0.2933, 0.4399, 0.3307, 0.9271, 0.8696],
        [0.3563, 0.7361, 0.6919, 0.0430, 0.0611, 0.0502]])
tensor([[0.5677, 0.1248],
        [0.1400, 0.2933],
        [0.3563, 0.7361]])
tensor([[0.6938, 0.7746],
        [0.4399, 0.3307],
        [0.6919, 0.0430]])
tensor([[0.0696, 0.1232],
        [0.9271, 0.8696],
        [0.0611, 0.0502]])


### split
- `chunck`와 동일한 기능이지만 조금 다름

- 하나의 텐서당 크기가 얼마이냐

In [ ]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1)  #나누어진 텐서의 크기

print(tensor)
print(t1)
print(t2)

tensor([[0.3422, 0.0234, 0.3142, 0.8835, 0.6983, 0.8281],
        [0.0601, 0.5513, 0.8923, 0.4863, 0.8072, 0.1993],
        [0.4833, 0.0586, 0.6967, 0.0998, 0.1127, 0.0389]])
tensor([[0.3422, 0.0234, 0.3142],
        [0.0601, 0.5513, 0.8923],
        [0.4833, 0.0586, 0.6967]])
tensor([[0.8835, 0.6983, 0.8281],
        [0.4863, 0.8072, 0.1993],
        [0.0998, 0.1127, 0.0389]])


### torch ↔ numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능

  - `numpy()`
  - `from_numpy()`

- (참고)
  - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [ ]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)    #메모리가 공유돼서 b값도 바뀜

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
- `.to` 메소드를 사용하여 텐서를 어떠한 장치로도 옮길 수 있음
  - 예) cpu, gpu

In [ ]:
import torch

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6051])
-0.6050900220870972
torch.float32


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(device)
print(z)
print(z.to("cpu", torch.double))

cuda
tensor([0.3949], device='cuda:0')
tensor([0.3949], dtype=torch.float64)


## AUTOGRAD (자동미분)
- autograd 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공

- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻

- backprop를 위한 미분값을 자동으로 계산

### Tensor

- data: tensor형태의 데이터

- grad: data가 겨쳐온 layer에 대한 미분값 저장

- grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

- `requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

- 계산이 완료된 후, `.backward()`를 호출하면 자동으로 `gradient`를 계산할 수 있으며, `.grad` 속성에 누적됨

- 기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad():`로 감싸면 `gradient`는 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

- Autograd 구현에서 매우 중요한 클래스 : `Function` 클래스

In [ ]:
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [ ]:
y = x + 5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
https://www.youtube.com/watch?v=C1P7PaIeKvU

- `requires_grad_(...)`는 기존 텐서의 `requires_grad`값을 바꿔치기(`in-place`)하여 변경

### 기울기(Gradient)
- 역전파: `.backward()`를 통해 역전파 계산 가능

- `with torch.no_grad()`를 사용하여 gradient의 업데이트를 하지 않음

- `detach()`: 내용물(content)은 같지만 require_grad가 다른 새로운 Tensor를 가져올 때

### 자동 미분 흐름 다시 보기(1)
- 계산 흐름  
  $a \rightarrow b  \rightarrow c  \rightarrow out $

<br>

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해  
  $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면  
    $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐


- $b = a + 2$

- $c = b^2$ 

- a의 `grad_fn`이 None인 이유  
  직접적으로 계산한 부분이 없었기 때문

### 자동 미분 흐름 다시 보기(2)
- `grad`값을 넣어서 `backward`

- 아래의 코드에서 `.grad`값이 None은 gradient값이 필요하지 않기 때문

## nn & nn.functional

- 두 패키지가 같은 기능이지만 방식이 조금 다름

- 위의 `autograd` 관련 작업들을 두 패키지를 통해 진행할 수 있음

- 텐서를 직접 다룰 때 `requires_grad`와 같은 방식으로 진행할 수 있음

- 결론적으로, `torch.nn`은 attribute를 활용해 state를 저장하고 활용하고,  
  `torch.nn.functional`로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능
 


### nn 패키지

- 주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때  
  - 따라서, `weight`값들을 직접 선언 안함

- 예시
  - Containers

  - Convolution Layers

  - Pooling layers

  - Padding Layers

  - Non-linear Activations (weighted sum, nonlinearity)

  - Non-linear Activations (other)

  - Normalization Layers

  - Recurrent Layers

  - Transformer Layers

  - Linear Layers

  - Dropout Layers

  - Sparse Layers

  - Distance Functions

  - Loss Functions

  - ..
- https://pytorch.org/docs/stable/nn.html



- Convolution Layer 예시 (1)


### nn.functional 패키지

- 가중치를 직접 선언하여 인자로 넣어줘야함

- 예시)
  - Convolution functions

  - Pooling functions
  
  - Non-linear activation functions

  - Normalization functions

  - Linear functions

  - Dropout functions
  
  - Sparse functions
  
  - Distance functions

  - Loss functions
  - ..

- https://pytorch.org/docs/stable/nn.functional.html

- Convolution Layer 예시 (2)

## Torchvision

- `transforms`: 전처리할 때 사용하는 메소드

- `transforms`에서 제공하는 클래스 이외에  
  일반적으로 클래스를 따로 만들어 전처리 단계를 진행
  
  - 아래의 코드에서 다양한 전처리 기술 확인  
    https://pytorch.org/docs/stable/torchvision/transforms.html


- 예시)
  - `DataLoader`의 인자로 들어갈 `transform`을 미리 정의할 수 있음

  - `Compose`를 통해 리스트 안에 순서대로 전처리 진행

  - 대표적인 예로, `ToTensor`()를 하는 이유는  
   <u>torchvision이 PIL Image형태로만 입력을 받기 때문에</u> 데이터 처리를 위해서 Tensor형으로 변환해야함

## utils.data

- `Dataset`에는 다양한 데이터셋이 존재  
  - MNIST, CIFAR10, ...

- `DataLoader`, `Dataset`을 통해  
  `batch_size`, `train`여부, `transform`등을 인자로 넣어 데이터를 어떻게 load할 것인지 정해줄 수 있음

- `batch_size`만큼 데이터를 하나씩 가져옴

<u>**(중요) torch에서는 channel(채널)이 앞에 옴**</u>

- `channel first`

- tensorflow, keras 등에서는 channel이 뒤에 옴(`channel last`)

### 데이터 확인

## 각 Layer 설명

### nn.Conv2d

- `in_channels`: channel의 갯수

- `out_channels`: 출력 채널의 갯수

- `kernel_size`: 커널(필터) 사이즈

- 텐서플로우, 케라스와 다르게 레이어의 `input`인자에도 값을 집어 넣어줘야함

- `wegiht`확인

- `weight`는 `detach()`를 통해 꺼내줘야 `numpy()`변환이 가능

### Pooling
- `F.max_pool2d` 
  - `stride`

  - `kernel_size`

- `torch.nn.MaxPool2d` 도 많이 사용

- MaxPool Layer는 weight가 없기 때문에 바로 `numpy()`변환 가능

### Linear
- 1d만 가능 `.view()`를 통해 1D로 펼쳐줘야함

### Softmax

### F.relu

- ReLU 함수를 적용하는 레이어

- `nn.ReLU`로도 사용 가능

## Optimizer

- `import torch.optim as optim`

- `model`의 파라미터를 업데이트

- 예시)
  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
  optimizer = optim.SGD(model.parameters(), lr=0.001)
  ```

- `.zero_grad()`로 초기화
- `.step()`으로 업데이트

